quick := ""
suites := "full"
_flags := if quick != "" { "-- --quick" } else { "" }

[private]
_bench name:
    cargo bench --bench {{name}} --features {{suites}} --manifest-path ../Cargo.toml {{_flags}}

common: (_bench "common")

ietf: (_bench "ietf")

pedersen: (_bench "pedersen")

ring: (_bench "ring")

all: common ietf pedersen ring
